---
- name: Check if Dotfiles-private repository exists
  stat:
    path: "{{ ansible_facts.env.HOME }}/Dotfiles-private/.git"
  register: private_repo

- name: Clone Dotfiles-private repository
  git:
    repo: git@github.com:livlikwav/Dotfiles-private.git
    dest: "{{ ansible_facts.env.HOME }}/Dotfiles-private"
    version: main
    accept_hostkey: yes
  when: not private_repo.stat.exists

- name: Run Dotfiles-private playbooks (entrypoint: ansible/playbooks/all.yml)
  command: ansible-playbook ansible/playbooks/all.yml
  args:
    chdir: "{{ ansible_facts.env.HOME }}/Dotfiles-private"
  environment:
    ANSIBLE_CONFIG: "{{ ansible_facts.env.HOME }}/Dotfiles-private/ansible/ansible.cfg"
  changed_when: true
